### ISSUE TITLE
Improve code quality

### ISSUE THREAD

**Issue by SharplEr** [filfreire/anagram#2]
I think it will be nice to remove `static` method form AnagramOf :)

**Comment by filfreire** [comment]
@SharplEr indeed, nice suggestion. I opened the PR #3 to tackle this issue.
Let me know what you think of the change there.

**Comment by filfreire** [comment]
@SharplEr also, thanks for opening an issue 👍

**Comment by filfreire** [comment]
@SharplEr merged PR #3

**Comment by filfreire** [comment]
@SharplEr I'm closing this issue since PR was merged. Feel free to open any other issues you see fit. Thank you :+1:
